package neu.quwanme.bean;

import java.io.Serializable;
import java.util.Date;

public class Activity implements Serializable{

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column activity.acticity_id
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	private Integer activityId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column activity.activity_name
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	private String activityName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column activity.activity_addr
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	private String activityAddr;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column activity.activity_start_time
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	private Date activityStartTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column activity.activity_end_time
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	private Date activityEndTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column activity.activity_cur_people
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	private Integer activityCurPeople;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column activity.activity_max_popu
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	private Integer activityMaxPopu;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column activity.activiity_min_popu
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	private Integer activiityMinPopu;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column activity.activity_popu
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	private Integer activityPopu;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column activity.activity_status
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	private Integer activityStatus;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column activity.activity_comment
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	private String activityComment;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column activity.acticity_id
	 * @return  the value of activity.acticity_id
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	public Integer getActivityId() {
		return activityId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column activity.acticity_id
	 * @param activityId  the value for activity.acticity_id
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	public void setActicityId(Integer activityId) {
		this.activityId = activityId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column activity.activity_name
	 * @return  the value of activity.activity_name
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	public String getActivityName() {
		return activityName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column activity.activity_name
	 * @param activityName  the value for activity.activity_name
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	public void setActivityName(String activityName) {
		this.activityName = activityName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column activity.activity_addr
	 * @return  the value of activity.activity_addr
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	public String getActivityAddr() {
		return activityAddr;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column activity.activity_addr
	 * @param activityAddr  the value for activity.activity_addr
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	public void setActivityAddr(String activityAddr) {
		this.activityAddr = activityAddr;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column activity.activity_start_time
	 * @return  the value of activity.activity_start_time
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	public Date getActivityStartTime() {
		return activityStartTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column activity.activity_start_time
	 * @param activityStartTime  the value for activity.activity_start_time
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	public void setActivityStartTime(Date activityStartTime) {
		this.activityStartTime = activityStartTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column activity.activity_end_time
	 * @return  the value of activity.activity_end_time
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	public Date getActivityEndTime() {
		return activityEndTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column activity.activity_end_time
	 * @param activityEndTime  the value for activity.activity_end_time
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	public void setActivityEndTime(Date activityEndTime) {
		this.activityEndTime = activityEndTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column activity.activity_cur_people
	 * @return  the value of activity.activity_cur_people
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	public Integer getActivityCurPeople() {
		return activityCurPeople;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column activity.activity_cur_people
	 * @param activityCurPeople  the value for activity.activity_cur_people
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	public void setActivityCurPeople(Integer activityCurPeople) {
		this.activityCurPeople = activityCurPeople;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column activity.activity_max_popu
	 * @return  the value of activity.activity_max_popu
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	public Integer getActivityMaxPopu() {
		return activityMaxPopu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column activity.activity_max_popu
	 * @param activityMaxPopu  the value for activity.activity_max_popu
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	public void setActivityMaxPopu(Integer activityMaxPopu) {
		this.activityMaxPopu = activityMaxPopu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column activity.activiity_min_popu
	 * @return  the value of activity.activiity_min_popu
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	public Integer getActiviityMinPopu() {
		return activiityMinPopu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column activity.activiity_min_popu
	 * @param activiityMinPopu  the value for activity.activiity_min_popu
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	public void setActiviityMinPopu(Integer activiityMinPopu) {
		this.activiityMinPopu = activiityMinPopu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column activity.activity_popu
	 * @return  the value of activity.activity_popu
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	public Integer getActivityPopu() {
		return activityPopu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column activity.activity_popu
	 * @param activityPopu  the value for activity.activity_popu
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	public void setActivityPopu(Integer activityPopu) {
		this.activityPopu = activityPopu;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column activity.activity_status
	 * @return  the value of activity.activity_status
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	public Integer getActivityStatus() {
		return activityStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column activity.activity_status
	 * @param activityStatus  the value for activity.activity_status
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	public void setActivityStatus(Integer activityStatus) {
		this.activityStatus = activityStatus;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column activity.activity_comment
	 * @return  the value of activity.activity_comment
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	public String getActivityComment() {
		return activityComment;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column activity.activity_comment
	 * @param activityComment  the value for activity.activity_comment
	 * @abatorgenerated  Fri Apr 08 14:32:52 CST 2016
	 */
	public void setActivityComment(String activityComment) {
		this.activityComment = activityComment;
	}
}