package neu.quwanme.bean;

public class ActivityCity {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activity_city.id
     *
     * @abatorgenerated Fri Apr 08 14:32:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activity_city.activity_id
     *
     * @abatorgenerated Fri Apr 08 14:32:52 CST 2016
     */
    private Integer activityId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activity_city.city_id
     *
     * @abatorgenerated Fri Apr 08 14:32:52 CST 2016
     */
    private Integer cityId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activity_city.id
     *
     * @return the value of activity_city.id
     *
     * @abatorgenerated Fri Apr 08 14:32:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activity_city.id
     *
     * @param id the value for activity_city.id
     *
     * @abatorgenerated Fri Apr 08 14:32:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activity_city.activity_id
     *
     * @return the value of activity_city.activity_id
     *
     * @abatorgenerated Fri Apr 08 14:32:52 CST 2016
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activity_city.activity_id
     *
     * @param activityId the value for activity_city.activity_id
     *
     * @abatorgenerated Fri Apr 08 14:32:52 CST 2016
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activity_city.city_id
     *
     * @return the value of activity_city.city_id
     *
     * @abatorgenerated Fri Apr 08 14:32:52 CST 2016
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activity_city.city_id
     *
     * @param cityId the value for activity_city.city_id
     *
     * @abatorgenerated Fri Apr 08 14:32:52 CST 2016
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }
}