package neu.quwanme.bean;

public class ActivityType {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column activity_type.activity_type_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	private Integer activityTypeId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column activity_type.activity_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	private Integer activityId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column activity_type.type_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	private Integer typeId;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column activity_type.activity_type_id
	 * @return  the value of activity_type.activity_type_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	public Integer getActivityTypeId() {
		return activityTypeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column activity_type.activity_type_id
	 * @param activityTypeId  the value for activity_type.activity_type_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	public void setActivityTypeId(Integer activityTypeId) {
		this.activityTypeId = activityTypeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column activity_type.activity_id
	 * @return  the value of activity_type.activity_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	public Integer getActivityId() {
		return activityId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column activity_type.activity_id
	 * @param activityId  the value for activity_type.activity_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	public void setActivityId(Integer activityId) {
		this.activityId = activityId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column activity_type.type_id
	 * @return  the value of activity_type.type_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	public Integer getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column activity_type.type_id
	 * @param typeId  the value for activity_type.type_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	@Override
	public String toString() {
		return "ActivityType [activityTypeId=" + activityTypeId + ", activityId=" + activityId + ", typeId=" + typeId
				+ "]";
	}
	
	
}