package neu.quwanme.bean;

import java.util.Date;

public class Activity {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activity.acticity_id
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private Integer acticityId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activity.activity_name
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private String activityName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activity.activity_addr
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private String activityAddr;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activity.acticity_start_time
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private Date acticityStartTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activity.acticity_end_time
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private Date acticityEndTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activity.acticity_max_popu
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private Integer acticityMaxPopu;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activity.acticity_min_popu
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private Integer acticityMinPopu;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activity.acticity_popu
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private Integer acticityPopu;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activity.acticity_status
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private Integer acticityStatus;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column activity.acticity_comment
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private String acticityComment;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activity.acticity_id
     *
     * @return the value of activity.acticity_id
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public Integer getActicityId() {
        return acticityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activity.acticity_id
     *
     * @param acticityId the value for activity.acticity_id
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setActicityId(Integer acticityId) {
        this.acticityId = acticityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activity.activity_name
     *
     * @return the value of activity.activity_name
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public String getActivityName() {
        return activityName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activity.activity_name
     *
     * @param activityName the value for activity.activity_name
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setActivityName(String activityName) {
        this.activityName = activityName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activity.activity_addr
     *
     * @return the value of activity.activity_addr
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public String getActivityAddr() {
        return activityAddr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activity.activity_addr
     *
     * @param activityAddr the value for activity.activity_addr
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setActivityAddr(String activityAddr) {
        this.activityAddr = activityAddr;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activity.acticity_start_time
     *
     * @return the value of activity.acticity_start_time
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public Date getActicityStartTime() {
        return acticityStartTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activity.acticity_start_time
     *
     * @param acticityStartTime the value for activity.acticity_start_time
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setActicityStartTime(Date acticityStartTime) {
        this.acticityStartTime = acticityStartTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activity.acticity_end_time
     *
     * @return the value of activity.acticity_end_time
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public Date getActicityEndTime() {
        return acticityEndTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activity.acticity_end_time
     *
     * @param acticityEndTime the value for activity.acticity_end_time
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setActicityEndTime(Date acticityEndTime) {
        this.acticityEndTime = acticityEndTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activity.acticity_max_popu
     *
     * @return the value of activity.acticity_max_popu
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public Integer getActicityMaxPopu() {
        return acticityMaxPopu;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activity.acticity_max_popu
     *
     * @param acticityMaxPopu the value for activity.acticity_max_popu
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setActicityMaxPopu(Integer acticityMaxPopu) {
        this.acticityMaxPopu = acticityMaxPopu;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activity.acticity_min_popu
     *
     * @return the value of activity.acticity_min_popu
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public Integer getActicityMinPopu() {
        return acticityMinPopu;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activity.acticity_min_popu
     *
     * @param acticityMinPopu the value for activity.acticity_min_popu
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setActicityMinPopu(Integer acticityMinPopu) {
        this.acticityMinPopu = acticityMinPopu;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activity.acticity_popu
     *
     * @return the value of activity.acticity_popu
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public Integer getActicityPopu() {
        return acticityPopu;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activity.acticity_popu
     *
     * @param acticityPopu the value for activity.acticity_popu
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setActicityPopu(Integer acticityPopu) {
        this.acticityPopu = acticityPopu;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activity.acticity_status
     *
     * @return the value of activity.acticity_status
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public Integer getActicityStatus() {
        return acticityStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activity.acticity_status
     *
     * @param acticityStatus the value for activity.acticity_status
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setActicityStatus(Integer acticityStatus) {
        this.acticityStatus = acticityStatus;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column activity.acticity_comment
     *
     * @return the value of activity.acticity_comment
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public String getActicityComment() {
        return acticityComment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column activity.acticity_comment
     *
     * @param acticityComment the value for activity.acticity_comment
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setActicityComment(String acticityComment) {
        this.acticityComment = acticityComment;
    }
}