package neu.quwanme.bean;

public class DealActivity {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column deal_activity.deal_activity_id
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private Integer dealActivityId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column deal_activity.deal_id
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private Integer dealId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column deal_activity.activity_id
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private Integer activityId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column deal_activity.deal_activity_id
     *
     * @return the value of deal_activity.deal_activity_id
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public Integer getDealActivityId() {
        return dealActivityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column deal_activity.deal_activity_id
     *
     * @param dealActivityId the value for deal_activity.deal_activity_id
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setDealActivityId(Integer dealActivityId) {
        this.dealActivityId = dealActivityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column deal_activity.deal_id
     *
     * @return the value of deal_activity.deal_id
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public Integer getDealId() {
        return dealId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column deal_activity.deal_id
     *
     * @param dealId the value for deal_activity.deal_id
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setDealId(Integer dealId) {
        this.dealId = dealId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column deal_activity.activity_id
     *
     * @return the value of deal_activity.activity_id
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column deal_activity.activity_id
     *
     * @param activityId the value for deal_activity.activity_id
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }
}