package neu.quwanme.bean;

import java.util.Date;

public class Deal {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column deal.deal_id
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private Integer dealId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column deal.deal_name
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private String dealName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column deal.deal_create_time
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private Date dealCreateTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column deal.deal_dead_time
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private Date dealDeadTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column deal.deal_dur_time
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private Long dealDurTime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column deal.deal_comment
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private String dealComment;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column deal.deal_id
     *
     * @return the value of deal.deal_id
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public Integer getDealId() {
        return dealId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column deal.deal_id
     *
     * @param dealId the value for deal.deal_id
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setDealId(Integer dealId) {
        this.dealId = dealId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column deal.deal_name
     *
     * @return the value of deal.deal_name
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public String getDealName() {
        return dealName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column deal.deal_name
     *
     * @param dealName the value for deal.deal_name
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setDealName(String dealName) {
        this.dealName = dealName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column deal.deal_create_time
     *
     * @return the value of deal.deal_create_time
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public Date getDealCreateTime() {
        return dealCreateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column deal.deal_create_time
     *
     * @param dealCreateTime the value for deal.deal_create_time
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setDealCreateTime(Date dealCreateTime) {
        this.dealCreateTime = dealCreateTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column deal.deal_dead_time
     *
     * @return the value of deal.deal_dead_time
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public Date getDealDeadTime() {
        return dealDeadTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column deal.deal_dead_time
     *
     * @param dealDeadTime the value for deal.deal_dead_time
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setDealDeadTime(Date dealDeadTime) {
        this.dealDeadTime = dealDeadTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column deal.deal_dur_time
     *
     * @return the value of deal.deal_dur_time
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public Long getDealDurTime() {
        return dealDurTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column deal.deal_dur_time
     *
     * @param dealDurTime the value for deal.deal_dur_time
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setDealDurTime(Long dealDurTime) {
        this.dealDurTime = dealDurTime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column deal.deal_comment
     *
     * @return the value of deal.deal_comment
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public String getDealComment() {
        return dealComment;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column deal.deal_comment
     *
     * @param dealComment the value for deal.deal_comment
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setDealComment(String dealComment) {
        this.dealComment = dealComment;
    }
}