package neu.quwanme.bean;

public class School {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column school.school_id
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private Integer schoolId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column school.school_name
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private String schoolName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column school.school_city
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private String schoolCity;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column school.school_id
     *
     * @return the value of school.school_id
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column school.school_id
     *
     * @param schoolId the value for school.school_id
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column school.school_name
     *
     * @return the value of school.school_name
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column school.school_name
     *
     * @param schoolName the value for school.school_name
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column school.school_city
     *
     * @return the value of school.school_city
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public String getSchoolCity() {
        return schoolCity;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column school.school_city
     *
     * @param schoolCity the value for school.school_city
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setSchoolCity(String schoolCity) {
        this.schoolCity = schoolCity;
    }

	@Override
	public String toString() {
		return "School [schoolId=" + schoolId + ", schoolName=" + schoolName + ", schoolCity=" + schoolCity + "]";
	}
    
    
}