package neu.quwanme.bean;

public class SchoolCity {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column school_city.school_city_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	private Integer schoolCityId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column school_city.city_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	private Integer cityId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column school_city.school_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	private Integer schoolId;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column school_city.school_city_id
	 * @return  the value of school_city.school_city_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	public Integer getSchoolCityId() {
		return schoolCityId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column school_city.school_city_id
	 * @param schoolCityId  the value for school_city.school_city_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	public void setSchoolCityId(Integer schoolCityId) {
		this.schoolCityId = schoolCityId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column school_city.city_id
	 * @return  the value of school_city.city_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	public Integer getCityId() {
		return cityId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column school_city.city_id
	 * @param cityId  the value for school_city.city_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column school_city.school_id
	 * @return  the value of school_city.school_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	public Integer getSchoolId() {
		return schoolId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column school_city.school_id
	 * @param schoolId  the value for school_city.school_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	public void setSchoolId(Integer schoolId) {
		this.schoolId = schoolId;
	}

	@Override
	public String toString() {
		return "SchoolCity [schoolCityId=" + schoolCityId + ", cityId=" + cityId + ", schoolId=" + schoolId + "]";
	}
	
}