package neu.quwanme.bean;

public class ShopActivity {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shop_activity.shop_activity_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    private Integer shopActivityId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shop_activity.shop_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    private Integer shopId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shop_activity.activity_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    private Integer activityId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shop_activity.shop_activity_id
     *
     * @return the value of shop_activity.shop_activity_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public Integer getShopActivityId() {
        return shopActivityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shop_activity.shop_activity_id
     *
     * @param shopActivityId the value for shop_activity.shop_activity_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public void setShopActivityId(Integer shopActivityId) {
        this.shopActivityId = shopActivityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shop_activity.shop_id
     *
     * @return the value of shop_activity.shop_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shop_activity.shop_id
     *
     * @param shopId the value for shop_activity.shop_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shop_activity.activity_id
     *
     * @return the value of shop_activity.activity_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shop_activity.activity_id
     *
     * @param activityId the value for shop_activity.activity_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }
}