package neu.quwanme.bean;

public class ShopDeal {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shop_deal.shop_deal_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    private Integer shopDealId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shop_deal.shop_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    private Integer shopId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column shop_deal.deal_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    private Integer dealId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shop_deal.shop_deal_id
     *
     * @return the value of shop_deal.shop_deal_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public Integer getShopDealId() {
        return shopDealId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shop_deal.shop_deal_id
     *
     * @param shopDealId the value for shop_deal.shop_deal_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public void setShopDealId(Integer shopDealId) {
        this.shopDealId = shopDealId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shop_deal.shop_id
     *
     * @return the value of shop_deal.shop_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shop_deal.shop_id
     *
     * @param shopId the value for shop_deal.shop_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column shop_deal.deal_id
     *
     * @return the value of shop_deal.deal_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public Integer getDealId() {
        return dealId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column shop_deal.deal_id
     *
     * @param dealId the value for shop_deal.deal_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public void setDealId(Integer dealId) {
        this.dealId = dealId;
    }
}