package neu.quwanme.bean;

public class ShopCity {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column shop_city.shop_city_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	private Integer shopCityId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column shop_city.shop_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	private Integer shopId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column shop_city.city_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	private Integer cityId;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column shop_city.shop_city_id
	 * @return  the value of shop_city.shop_city_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	public Integer getShopCityId() {
		return shopCityId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column shop_city.shop_city_id
	 * @param shopCityId  the value for shop_city.shop_city_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	public void setShopCityId(Integer shopCityId) {
		this.shopCityId = shopCityId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column shop_city.shop_id
	 * @return  the value of shop_city.shop_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	public Integer getShopId() {
		return shopId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column shop_city.shop_id
	 * @param shopId  the value for shop_city.shop_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	public void setShopId(Integer shopId) {
		this.shopId = shopId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column shop_city.city_id
	 * @return  the value of shop_city.city_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	public Integer getCityId() {
		return cityId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column shop_city.city_id
	 * @param cityId  the value for shop_city.city_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	@Override
	public String toString() {
		return "ShopCity [shopCityId=" + shopCityId + ", shopId=" + shopId + ", cityId=" + cityId + "]";
	}
	
}