package neu.quwanme.bean;

import java.io.Serializable;

public class Shop implements Serializable{
    /**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column shop.shop_id
	 * @abatorgenerated  Mon Apr 11 11:53:32 CST 2016
	 */
	private Integer shopId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column shop.shop_name
	 * @abatorgenerated  Mon Apr 11 11:53:32 CST 2016
	 */
	private String shopName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column shop.shop_city
	 * @abatorgenerated  Mon Apr 11 11:53:32 CST 2016
	 */
	private String shopCity;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column shop.shop_type
	 * @abatorgenerated  Mon Apr 11 11:53:32 CST 2016
	 */
	private String shopType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column shop.shop_password
	 * @abatorgenerated  Mon Apr 11 11:53:32 CST 2016
	 */
	private String shopPassword;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column shop.shop_id
	 * @return  the value of shop.shop_id
	 * @abatorgenerated  Mon Apr 11 11:53:32 CST 2016
	 */
	public Integer getShopId() {
		return shopId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column shop.shop_id
	 * @param shopId  the value for shop.shop_id
	 * @abatorgenerated  Mon Apr 11 11:53:32 CST 2016
	 */
	public void setShopId(Integer shopId) {
		this.shopId = shopId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column shop.shop_name
	 * @return  the value of shop.shop_name
	 * @abatorgenerated  Mon Apr 11 11:53:32 CST 2016
	 */
	public String getShopName() {
		return shopName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column shop.shop_name
	 * @param shopName  the value for shop.shop_name
	 * @abatorgenerated  Mon Apr 11 11:53:32 CST 2016
	 */
	public void setShopName(String shopName) {
		this.shopName = shopName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column shop.shop_city
	 * @return  the value of shop.shop_city
	 * @abatorgenerated  Mon Apr 11 11:53:32 CST 2016
	 */
	public String getShopCity() {
		return shopCity;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column shop.shop_city
	 * @param shopCity  the value for shop.shop_city
	 * @abatorgenerated  Mon Apr 11 11:53:32 CST 2016
	 */
	public void setShopCity(String shopCity) {
		this.shopCity = shopCity;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column shop.shop_type
	 * @return  the value of shop.shop_type
	 * @abatorgenerated  Mon Apr 11 11:53:32 CST 2016
	 */
	public String getShopType() {
		return shopType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column shop.shop_type
	 * @param shopType  the value for shop.shop_type
	 * @abatorgenerated  Mon Apr 11 11:53:32 CST 2016
	 */
	public void setShopType(String shopType) {
		this.shopType = shopType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column shop.shop_password
	 * @return  the value of shop.shop_password
	 * @abatorgenerated  Mon Apr 11 11:53:32 CST 2016
	 */
	public String getShopPassword() {
		return shopPassword;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column shop.shop_password
	 * @param shopPassword  the value for shop.shop_password
	 * @abatorgenerated  Mon Apr 11 11:53:32 CST 2016
	 */
	public void setShopPassword(String shopPassword) {
		this.shopPassword = shopPassword;
	}

	@Override
	public String toString() {
		return "Shop [shopId=" + shopId + ", shopName=" + shopName + ", shopCity=" + shopCity + ", shopType=" + shopType
				+ ", shopPassword=" + shopPassword + "]";
	}

	
    
}