package neu.quwanme.bean;

public class Type {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column type.type_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	private Integer typeId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column type.type_name
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	private String typeName;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column type.type_id
	 * @return  the value of type.type_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	public Integer getTypeId() {
		return typeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column type.type_id
	 * @param typeId  the value for type.type_id
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column type.type_name
	 * @return  the value of type.type_name
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	public String getTypeName() {
		return typeName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column type.type_name
	 * @param typeName  the value for type.type_name
	 * @abatorgenerated  Fri Apr 08 12:04:43 CST 2016
	 */
	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Override
	public String toString() {
		return "Type [typeId=" + typeId + ", typeName=" + typeName + "]";
	}
	
}