package neu.quwanme.bean;

public class UserSchool {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_school.iduser_school_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    private Integer iduserSchoolId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_school.user_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_school.school_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    private Integer schoolId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_school.iduser_school_id
     *
     * @return the value of user_school.iduser_school_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public Integer getIduserSchoolId() {
        return iduserSchoolId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_school.iduser_school_id
     *
     * @param iduserSchoolId the value for user_school.iduser_school_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public void setIduserSchoolId(Integer iduserSchoolId) {
        this.iduserSchoolId = iduserSchoolId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_school.user_id
     *
     * @return the value of user_school.user_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_school.user_id
     *
     * @param userId the value for user_school.user_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_school.school_id
     *
     * @return the value of user_school.school_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public Integer getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_school.school_id
     *
     * @param schoolId the value for user_school.school_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public void setSchoolId(Integer schoolId) {
        this.schoolId = schoolId;
    }
}