package neu.quwanme.bean;

public class UserActivity {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_activity.user_activity_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    private Integer userActivityId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_activity.user_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_activity.activity_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    private Integer activityId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_activity.user_activity_id
     *
     * @return the value of user_activity.user_activity_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public Integer getUserActivityId() {
        return userActivityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_activity.user_activity_id
     *
     * @param userActivityId the value for user_activity.user_activity_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public void setUserActivityId(Integer userActivityId) {
        this.userActivityId = userActivityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_activity.user_id
     *
     * @return the value of user_activity.user_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_activity.user_id
     *
     * @param userId the value for user_activity.user_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_activity.activity_id
     *
     * @return the value of user_activity.activity_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_activity.activity_id
     *
     * @param activityId the value for user_activity.activity_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }
}