package neu.quwanme.bean;

public class UserDeal {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_deal.user_deal_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    private Integer userDealId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_deal.user_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user_deal.deal_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    private Integer dealId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_deal.user_deal_id
     *
     * @return the value of user_deal.user_deal_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public Integer getUserDealId() {
        return userDealId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_deal.user_deal_id
     *
     * @param userDealId the value for user_deal.user_deal_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public void setUserDealId(Integer userDealId) {
        this.userDealId = userDealId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_deal.user_id
     *
     * @return the value of user_deal.user_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_deal.user_id
     *
     * @param userId the value for user_deal.user_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user_deal.deal_id
     *
     * @return the value of user_deal.deal_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public Integer getDealId() {
        return dealId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user_deal.deal_id
     *
     * @param dealId the value for user_deal.deal_id
     *
     * @abatorgenerated Wed Feb 24 18:13:40 CST 2016
     */
    public void setDealId(Integer dealId) {
        this.dealId = dealId;
    }
}