package neu.quwanme.bean;

public class User {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user.user_id
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user.user_number
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private Integer userNumber;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user.user_real_name
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private String userRealName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user.user_nick_name
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private String userNickName;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user.user_password
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private String userPassword;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user.user_age
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private Integer userAge;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user.user_sex
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    private String userSex;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user.user_id
     *
     * @return the value of user.user_id
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user.user_number
     *
     * @return the value of user.user_number
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public Integer getUserNumber() {
        return userNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user.user_number
     *
     * @param userNumber the value for user.user_number
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setUserNumber(Integer userNumber) {
        this.userNumber = userNumber;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user.user_real_name
     *
     * @return the value of user.user_real_name
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public String getUserRealName() {
        return userRealName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user.user_real_name
     *
     * @param userRealName the value for user.user_real_name
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setUserRealName(String userRealName) {
        this.userRealName = userRealName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user.user_nick_name
     *
     * @return the value of user.user_nick_name
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public String getUserNickName() {
        return userNickName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user.user_nick_name
     *
     * @param userNickName the value for user.user_nick_name
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setUserNickName(String userNickName) {
        this.userNickName = userNickName;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user.user_password
     *
     * @return the value of user.user_password
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user.user_password
     *
     * @param userPassword the value for user.user_password
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user.user_age
     *
     * @return the value of user.user_age
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public Integer getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user.user_age
     *
     * @param userAge the value for user.user_age
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setUserAge(Integer userAge) {
        this.userAge = userAge;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user.user_sex
     *
     * @return the value of user.user_sex
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user.user_sex
     *
     * @param userSex the value for user.user_sex
     *
     * @abatorgenerated Wed Feb 24 18:13:39 CST 2016
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex;
    }

	@Override
	public String toString() {
		return "User [userId=" + userId + ", userNumber=" + userNumber + ", userRealName=" + userRealName
				+ ", userNickName=" + userNickName + ", userPassword=" + userPassword + ", userAge=" + userAge
				+ ", userSex=" + userSex + "]";
	}
    
    
}